controllers:
    resource: ../src/Controller/
    type: annotation
    prefix: /api
    
api_login_check:
    path: /api/login_check

kernel:
    resource: ../src/Kernel.php
    type: annotation

images_avatar:
    path: /images/{filename}
    controller: App\Controller\ImageController::show
